services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: epilink_db
      POSTGRES_USER: epilink
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/seeds/egypt_des_diseases.sql:/docker-entrypoint-initdb.d/01_seed.sql

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
