-- EpiLink Egypt DES Disease Registry Seed
-- Group A: Immediate alert (alert_minutes = 60)
-- Group B: Weekly reporting (alert_minutes = NULL)

INSERT INTO diseases (id, icd10_code, name, group_label, alert_minutes) VALUES
-- GROUP A — Immediate
(gen_random_uuid(), 'A80', 'Acute Flaccid Paralysis / Poliomyelitis', 'A', 60),
(gen_random_uuid(), 'A36', 'Diphtheria', 'A', 60),
(gen_random_uuid(), 'A37', 'Pertussis (Whooping Cough)', 'A', 60),
(gen_random_uuid(), 'A33', 'Neonatal Tetanus', 'A', 60),
(gen_random_uuid(), 'U07.1', 'COVID-19', 'A', 60),
(gen_random_uuid(), 'B34.2', 'MERS-CoV', 'A', 60),
(gen_random_uuid(), 'A39.0', 'Meningococcal Meningitis', 'A', 60),
(gen_random_uuid(), 'G00', 'Bacterial Meningitis', 'A', 60),
(gen_random_uuid(), 'A87', 'Viral Meningitis', 'A', 60),
(gen_random_uuid(), 'A05.0', 'Acute Food Poisoning', 'A', 60),
(gen_random_uuid(), 'A82', 'Rabies', 'A', 60),
(gen_random_uuid(), 'A92.4', 'Rift Valley Fever', 'A', 60),
(gen_random_uuid(), 'A20', 'Plague', 'A', 60),
(gen_random_uuid(), 'B50', 'Malaria (P. falciparum)', 'A', 60),
(gen_random_uuid(), 'B51', 'Malaria (P. vivax)', 'A', 60),
(gen_random_uuid(), 'B20', 'HIV / AIDS', 'A', 60),
(gen_random_uuid(), 'U06.9', 'Zika Virus Disease', 'A', 60),
(gen_random_uuid(), 'B04', 'Mpox (Monkeypox)', 'A', 60),
(gen_random_uuid(), 'B05', 'Measles', 'A', 60),
(gen_random_uuid(), 'B06', 'Rubella', 'A', 60),
(gen_random_uuid(), 'B26_MU', 'Mumps', 'A', 60),
(gen_random_uuid(), 'J09', 'Avian Influenza H5N1', 'A', 60),
(gen_random_uuid(), 'A00.1', 'Cholera', 'A', 60),
(gen_random_uuid(), 'A86', 'Viral Encephalitis', 'A', 60),
(gen_random_uuid(), 'A05.1', 'Botulism', 'A', 60),
(gen_random_uuid(), 'A22', 'Anthrax', 'A', 60),
(gen_random_uuid(), 'A98.0', 'Crimean-Congo Hemorrhagic Fever', 'A', 60),
(gen_random_uuid(), 'A92.3', 'West Nile Fever', 'A', 60),
(gen_random_uuid(), 'A98.4', 'Ebola Virus Disease', 'A', 60),
(gen_random_uuid(), 'A97', 'Dengue Hemorrhagic Fever', 'A', 60),
(gen_random_uuid(), 'A95', 'Yellow Fever', 'A', 60),
(gen_random_uuid(), 'PHE.ANY', 'Any Public Health Event of Concern', 'A', 60),

-- GROUP B — Weekly
(gen_random_uuid(), 'B26', 'Viral Hepatitis (A, B, C, E)', 'B', NULL),
(gen_random_uuid(), 'A01.0', 'Typhoid Fever', 'B', NULL),
(gen_random_uuid(), 'A04.0', 'Bloody Diarrhea / Dysentery', 'B', NULL),
(gen_random_uuid(), 'A23', 'Brucellosis', 'B', NULL),
(gen_random_uuid(), 'T01.9', 'Animal Bite', 'B', NULL),
(gen_random_uuid(), 'B74', 'Filariasis', 'B', NULL),
(gen_random_uuid(), 'B01', 'Chickenpox (Varicella)', 'B', NULL),
(gen_random_uuid(), 'J10', 'Seasonal Influenza', 'B', NULL),
(gen_random_uuid(), 'A15', 'Tuberculosis (TB)', 'B', NULL),
(gen_random_uuid(), 'A30', 'Leprosy', 'B', NULL),
(gen_random_uuid(), 'B55', 'Leishmaniasis', 'B', NULL),
(gen_random_uuid(), 'B66', 'Fascioliasis', 'B', NULL),
(gen_random_uuid(), 'B65', 'Schistosomiasis (Bilharzia)', 'B', NULL);